"""reset schema limpio

Revision ID: 4392cb5fd4b3
Revises: 7f72858483be
Create Date: 2025-11-08 19:35:49.730143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4392cb5fd4b3'
down_revision = '7f72858483be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jeans')
    op.drop_table('transactions')
    op.drop_table('blusones')
    op.drop_table('compras')
    op.drop_table('blusas')
    op.drop_table('enterizos')
    op.drop_table('usuarios')
    op.drop_table('vestidos')
    op.drop_table('vestidosgala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vestidosgala',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talla', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('chk_vestidosgala_stock')),
    sa.PrimaryKeyConstraint('id', name=op.f('vestidosgala_pkey'))
    )
    op.create_table('vestidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talla', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('chk_vestidos_stock')),
    sa.PrimaryKeyConstraint('id', name=op.f('vestidos_pkey'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contrasena_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nombre_completo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('rol', sa.VARCHAR(length=20), server_default=sa.text("'cliente'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nombre_usuario', name=op.f('usuarios_nombre_usuario_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('enterizos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talla', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('chk_enterizos_stock')),
    sa.PrimaryKeyConstraint('id', name=op.f('enterizos_pkey'))
    )
    op.create_table('blusas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talla', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('chk_blusas_stock')),
    sa.PrimaryKeyConstraint('id', name=op.f('blusas_pkey'))
    )
    op.create_table('compras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_cliente', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('producto', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('cantidad > 0', name=op.f('chk_compras_cantidad')),
    sa.CheckConstraint('total >= 0::numeric', name=op.f('chk_compras_total')),
    sa.PrimaryKeyConstraint('id', name=op.f('compras_pkey'))
    )
    op.create_table('blusones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talla', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('chk_blusones_stock')),
    sa.PrimaryKeyConstraint('id', name=op.f('blusones_pkey'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tx_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=20), server_default=sa.text("'card_fake'::character varying"), autoincrement=False, nullable=True),
    sa.Column('card_last4', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('card_brand', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey')),
    sa.UniqueConstraint('tx_id', name=op.f('transactions_tx_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('jeans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talla', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('chk_jeans_stock')),
    sa.PrimaryKeyConstraint('id', name=op.f('jeans_pkey'))
    )
    # ### end Alembic commands ###
