"""Agregar columna stock

Revision ID: 828c5c865721
Revises: 
Create Date: 2025-10-26 09:47:05.227002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '828c5c865721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blusas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('blusones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('enterizos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('vestidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('vestidosgala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vestidosgala', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('stock')

    with op.batch_alter_table('vestidos', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('stock')

    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('stock')

    with op.batch_alter_table('enterizos', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('stock')

    with op.batch_alter_table('blusones', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('stock')

    with op.batch_alter_table('blusas', schema=None) as batch_op:
        batch_op.drop_column('stock')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
